# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 560313aaf65083497256e1ebdf4d3dd35bb3a139a16abfa2589b6ecd4633aecf9e19b1559ec5c4e53f51a7ae3347ec3c61d44f73276136c283e83c21b21763b1

test:
  domain_name: example.com 
  secret_key_base: 1eb6c8fa78d5db2f1c4b81428a29e39bda5192f0d6caaeb2e8ba36c0606897e7920aef134b76f3c85108d6b40aa5116c957e992bd99b27e88a17b8e91f7b0bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
